/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BossTable: typeof import('./src/components/bossTable.vue')['default']
    Demo: typeof import('./src/components/no-bad-table/demo.vue')['default']
    EveryCheckGroup: typeof import('./src/components/every-form/every-checkGroup.vue')['default']
    EveryForm: typeof import('./src/components/every-form/index.vue')['default']
    FormItem: typeof import('./src/components/every-form/formItem.vue')['default']
    Label: typeof import('./src/components/every-form/label.vue')['default']
    Liusheng22Barcode: typeof import('./src/components/liusheng22-barcode/liusheng22-barcode.vue')['default']
    Loading: typeof import('./src/components/no-bad-table/loading.vue')['default']
    OrderTable: typeof import('./src/components/orderTable.vue')['default']
    PhoneInput: typeof import('./src/components/phoneInput.vue')['default']
    PopupPlus: typeof import('./src/components/popup-plus.vue')['default']
    SelectLabel: typeof import('./src/components/every-form/selectLabel.vue')['default']
    Table: typeof import('./src/components/no-bad-table/table.vue')['default']
  }
}
