# -*- coding: utf-8 -*-

"""
Prompts package for customer complaint analysis
"""

from .complaint_prompts import (
    COMPLAINT_DOMAIN_PROMPT_TEMPLATE,
    COMPLAINT_COLLECTION_INTENT_PROMPT_TEMPLATE,
    COMPLAINT_FEE_INTENT_PROMPT_TEMPLATE,
    COMPLAINT_CREDIT_INTENT_PROMPT_TEMPLATE,
    COMPLAINT_OTHER_INTENT_PROMPT_TEMPLATE,
    COMPLAINT_COLLECTION_VIOLATION_PROMPT_TEMPLATE,
    COMPLAINT_COLLECTION_CONSULT_PROMPT_TEMPLATE,
    COMPLAINT_FEE_DISPUTE_PROMPT_TEMPLATE,
    COMPLAINT_FEE_NEGOTIATION_PROMPT_TEMPLATE,
    COMPLAINT_CREDIT_DISPUTE_PROMPT_TEMPLATE,
    COMPLAINT_FEE_PAYMENT_EXCEPTION_PROMPT_TEMPLATE,
    COMPLAINT_DOCUMENT_PROCESSING_PROMPT_TEMPLATE
)

from .solution_prompts import (
    SOLUTION_DOMAIN_PROMPT_TEMPLATE,
    SOLUTION_COLLECTION_INTENT_PROMPT_TEMPLATE,
    SOLUTION_FEE_INTENT_PROMPT_TEMPLATE,
    SOLUTION_CREDIT_INTENT_PROMPT_TEMPLATE,
    SOLUTION_OTHER_INTENT_PROMPT_TEMPLATE,
    SOLUTION_STOP_COLLECTION_PROMPT_TEMPLATE,
    SOLUTION_REFUND_COMPENSATE_PROMPT_TEMPLATE,
    SOLUTION_REPAYMENT_NEGOTIATION_PROMPT_TEMPLATE,
    SOLUTION_COMFORT_APOLOGY_PROMPT_TEMPLATE,
    SOLUTION_DOCUMENT_PROCESSING_PROMPT_TEMPLATE,
    SOLUTION_UPGRADE_FEEDBACK_PROMPT_TEMPLATE
)

from .appeal_prompts import (
    APPEAL_DOMAIN_PROMPT_TEMPLATE,
    APPEAL_COLLECTION_INTENT_PROMPT_TEMPLATE,
    APPEAL_FEE_INTENT_PROMPT_TEMPLATE,
    APPEAL_CREDIT_INTENT_PROMPT_TEMPLATE,
    APPEAL_OTHER_INTENT_PROMPT_TEMPLATE,
    APPEAL_STOP_COLLECTION_PROMPT_TEMPLATE,
    APPEAL_REFUND_COMPENSATE_PROMPT_TEMPLATE,
    APPEAL_REPAYMENT_NEGOTIATION_PROMPT_TEMPLATE,
    APPEAL_COMFORT_APOLOGY_PROMPT_TEMPLATE,
    APPEAL_DOCUMENT_PROCESSING_PROMPT_TEMPLATE
)

from .reconciliation_prompts import (
    RECONCILIATION_PROMPT_TEMPLATE
)

from .basis_prompts import (
    COMPLAINT_BASIS_PROMPT_TEMPLATE,
    APPEAL_BASIS_PROMPT_TEMPLATE,
    SOLUTION_BASIS_PROMPT_TEMPLATE
)

__all__ = [
    "COMPLAINT_DOMAIN_PROMPT_TEMPLATE",
    "COMPLAINT_COLLECTION_INTENT_PROMPT_TEMPLATE",
    "COMPLAINT_FEE_INTENT_PROMPT_TEMPLATE",
    "COMPLAINT_CREDIT_INTENT_PROMPT_TEMPLATE",
    "COMPLAINT_OTHER_INTENT_PROMPT_TEMPLATE",
    "COMPLAINT_COLLECTION_VIOLATION_PROMPT_TEMPLATE",
    "COMPLAINT_COLLECTION_CONSULT_PROMPT_TEMPLATE",
    "COMPLAINT_FEE_DISPUTE_PROMPT_TEMPLATE",
    "COMPLAINT_FEE_NEGOTIATION_PROMPT_TEMPLATE",
    "COMPLAINT_CREDIT_DISPUTE_PROMPT_TEMPLATE",
    "COMPLAINT_FEE_PAYMENT_EXCEPTION_PROMPT_TEMPLATE",
    "COMPLAINT_DOCUMENT_PROCESSING_PROMPT_TEMPLATE",
    "RECONCILIATION_PROMPT_TEMPLATE",
    "SOLUTION_DOMAIN_PROMPT_TEMPLATE",
    "SOLUTION_COLLECTION_INTENT_PROMPT_TEMPLATE",
    "SOLUTION_FEE_INTENT_PROMPT_TEMPLATE",
    "SOLUTION_CREDIT_INTENT_PROMPT_TEMPLATE",
    "SOLUTION_OTHER_INTENT_PROMPT_TEMPLATE",
    "SOLUTION_STOP_COLLECTION_PROMPT_TEMPLATE",
    "SOLUTION_REFUND_COMPENSATE_PROMPT_TEMPLATE",
    "SOLUTION_REPAYMENT_NEGOTIATION_PROMPT_TEMPLATE",
    "SOLUTION_COMFORT_APOLOGY_PROMPT_TEMPLATE",
    "SOLUTION_DOCUMENT_PROCESSING_PROMPT_TEMPLATE",
    "SOLUTION_UPGRADE_FEEDBACK_PROMPT_TEMPLATE",
    "APPEAL_DOMAIN_PROMPT_TEMPLATE",
    "APPEAL_COLLECTION_INTENT_PROMPT_TEMPLATE",
    "APPEAL_FEE_INTENT_PROMPT_TEMPLATE",
    "APPEAL_CREDIT_INTENT_PROMPT_TEMPLATE",
    "APPEAL_OTHER_INTENT_PROMPT_TEMPLATE",
    "APPEAL_STOP_COLLECTION_PROMPT_TEMPLATE",
    "APPEAL_REFUND_COMPENSATE_PROMPT_TEMPLATE",
    "APPEAL_REPAYMENT_NEGOTIATION_PROMPT_TEMPLATE",
    "APPEAL_COMFORT_APOLOGY_PROMPT_TEMPLATE",
    "APPEAL_DOCUMENT_PROCESSING_PROMPT_TEMPLATE",
    "COMPLAINT_BASIS_PROMPT_TEMPLATE",
    "APPEAL_BASIS_PROMPT_TEMPLATE",
    "SOLUTION_BASIS_PROMPT_TEMPLATE"
]